// Version information
#define HEXICORD_VERSION "0.1."
#define HEXICORD_SEMVER  "0.1.0+g756166e"
/* #undef HEXICORD_VERSION_MAJOR */
#define HEXICORD_VERSION_MINOR 0
/* #undef HEXICORD_VERSION_PATCH */

// Customization
/* #undef HEXICORD_DEBUG_LOG */
/* #undef HEXICORD_DEBUG_CLIENT */
/* #undef HEXICORD_DEBUG_RATELIMITLOCK */
/* #undef HEXICORD_RATELIMIT_PREDICTION */
/* #undef HEXICORD_RATELIMIT_HIT_AS_ERROR */
#define HEXICORD_RATELIMIT_CACHE_SIZE 512
